[build]
  command = "cd netlify/functions && npm install"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[functions]
  node_bundler = "esbuild"

# Règles de réécriture pour le routage côté client
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Règles pour les appels API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200